version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.2
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      DEFAULT_VECTORIZER_MODULE: '' # Disable built-in vectorizer (we're using external)

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    ports:
      - "8082:80"
    environment:
      MODEL_ID: thenlper/gte-base
